// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BuzzTrackerAPIClient is the client API for BuzzTrackerAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BuzzTrackerAPIClient interface {
	GetBeer(ctx context.Context, in *GetBeerRequest, opts ...grpc.CallOption) (*GetBeerResponse, error)
}

type buzzTrackerAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewBuzzTrackerAPIClient(cc grpc.ClientConnInterface) BuzzTrackerAPIClient {
	return &buzzTrackerAPIClient{cc}
}

func (c *buzzTrackerAPIClient) GetBeer(ctx context.Context, in *GetBeerRequest, opts ...grpc.CallOption) (*GetBeerResponse, error) {
	out := new(GetBeerResponse)
	err := c.cc.Invoke(ctx, "/buzztracker.api.alpha.BuzzTrackerAPI/GetBeer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuzzTrackerAPIServer is the server API for BuzzTrackerAPI service.
// All implementations must embed UnimplementedBuzzTrackerAPIServer
// for forward compatibility
type BuzzTrackerAPIServer interface {
	GetBeer(context.Context, *GetBeerRequest) (*GetBeerResponse, error)
}

// UnimplementedBuzzTrackerAPIServer must be embedded to have forward compatible implementations.
type UnimplementedBuzzTrackerAPIServer struct {
}

func (UnimplementedBuzzTrackerAPIServer) GetBeer(context.Context, *GetBeerRequest) (*GetBeerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBeer not implemented")
}
func (UnimplementedBuzzTrackerAPIServer) mustEmbedUnimplementedBuzzTrackerAPIServer() {}

// UnsafeBuzzTrackerAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BuzzTrackerAPIServer will
// result in compilation errors.
type UnsafeBuzzTrackerAPIServer interface {
	mustEmbedUnimplementedBuzzTrackerAPIServer()
}

func RegisterBuzzTrackerAPIServer(s grpc.ServiceRegistrar, srv BuzzTrackerAPIServer) {
	s.RegisterService(&BuzzTrackerAPI_ServiceDesc, srv)
}

func _BuzzTrackerAPI_GetBeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuzzTrackerAPIServer).GetBeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/buzztracker.api.alpha.BuzzTrackerAPI/GetBeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuzzTrackerAPIServer).GetBeer(ctx, req.(*GetBeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BuzzTrackerAPI_ServiceDesc is the grpc.ServiceDesc for BuzzTrackerAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BuzzTrackerAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "buzztracker.api.alpha.BuzzTrackerAPI",
	HandlerType: (*BuzzTrackerAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBeer",
			Handler:    _BuzzTrackerAPI_GetBeer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "buzztracker.proto",
}
